# Generated by Django 4.1.7 on 2024-01-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('specilite', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(max_length=1)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('fait', models.BooleanField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.TextField()),
                ('medecin', models.ManyToManyField(related_name='visite', to='app.medecin')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visite', to='app.record')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('medecin', models.ManyToManyField(related_name='vaccination', to='app.medecin')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination', to='app.record')),
            ],
        ),
        migrations.CreateModel(
            name='Hopitalisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duree', models.DurationField()),
                ('result', models.TextField()),
                ('medecin', models.ManyToManyField(related_name='hospitalisation', to='app.medecin')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalisation', to='app.record')),
            ],
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.TextField()),
                ('medecin', models.ManyToManyField(related_name='control', to='app.medecin')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control', to='app.record')),
            ],
        ),
        migrations.CreateModel(
            name='Chirurgie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('detail', models.TextField()),
                ('duree', models.DurationField()),
                ('medecin', models.ManyToManyField(related_name='chirurgie', to='app.medecin')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chirurgie', to='app.record')),
            ],
        ),
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('medecin', models.ManyToManyField(related_name='analyse', to='app.medecin')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analyse', to='app.record')),
            ],
        ),
    ]
