# Generated by Django 4.1.7 on 2024-01-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_record_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hopitalisation',
            new_name='Hospitalisation',
        ),
        migrations.RenameField(
            model_name='analyse',
            old_name='result',
            new_name='resultat',
        ),
        migrations.RenameField(
            model_name='control',
            old_name='result',
            new_name='resultat',
        ),
        migrations.RenameField(
            model_name='hospitalisation',
            old_name='result',
            new_name='resultat',
        ),
        migrations.RenameField(
            model_name='visite',
            old_name='result',
            new_name='resultat',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='specilite',
        ),
        migrations.AddField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyse',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
